version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    container_name: clientbooker_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: America/Sao_Paulo
    ports:
      - "5433:5432"
    volumes:
      - clientbooker_pgdata:/var/lib/postgresql/data

volumes:
  clientbooker_pgdata: